title: mi primer GitHub
author: Avril1207
email: your-email@domain.com
description: well I'm very happy that today I can talk about how I get here ğŸ¤ğŸ˜€ğŸ¤ğŸ˜€ğŸ¤ğŸ˜€ğŸ¤ğŸ˜€ğŸ¤ğŸ˜€ğŸ¤ğŸ˜€ğŸ¤ğŸ˜€ğŸ¤ğŸ˜€ğŸ¤
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
